# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.7"
manifest_format = "2.0"
project_hash = "7328c540e4edf884b838b41f988e2b7567d84c8e"

[[deps.Boolean]]
path = "."
uuid = "d4def8ba-741e-4784-adc0-3f6248bfb1a9"
version = "2.0.0"
